# The URL the site will be built for
base_url = "https://blog.carrio.dev"

theme = "0xc-dark"

output_dir = "public"

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "base16-ateliersavanna.dark"
extra_syntaxes_and_themes = ["themes/0xc-dark/highlight_themes"]

[extra]
after_dark_title = "0xc :: a blog by tcarrio on tech, open source, and more"
after_dark_menu = [
    {url = "$BASE_URL", name = "Home"},
    # {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "https://tom.carrio.dev", name = "Profile"},
    {url = "https://github.com/tcarrio", name = "GitHub"},
    {url = "https://docs.google.com/viewer?url=https://docs.google.com/document/d/1ur6r_SJm0j2ETTJNG0GLsf3t671W5NuBo-RLl0-T25k/export?format=pdf", name = "CV"},
]


author = "Tom Carrio"
