# The URL the site will be built for
base_url = "https://blog.carrio.dev"

theme = "0xc-dark"

output_dir = "public"

generate_feeds = true
feed_filename = "rss.xml"

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "base16-ateliersavanna.dark"
extra_syntaxes_and_themes = ["themes/0xc-dark/highlight_themes"]

[extra]

author = "Tom Carrio"

[extra.after_dark]

[extra.after_dark.home]
menu = [
    {url = "$BASE_URL", name = "Home", icon = "house-simple"},
    {url = "$BASE_URL/blog", name = "Blog", icon = "article"},
    {url = "https://github.com/tcarrio", name = "GitHub", icon = "github-logo"},
    {url = "https://types.pl/@0xc", name = "Mastodon", icon = "mastodon-logo"},
    {url = "https://docs.google.com/viewer?url=https://docs.google.com/document/d/1ur6r_SJm0j2ETTJNG0GLsf3t671W5NuBo-RLl0-T25k/export?format=pdf", name = "CV", icon = "read-cv-logo"},
]
only_icons = true
photo = "https://avatars.githubusercontent.com/u/8659099?v=4"
title = "<i class=\"ph ph-bounding-box\"></i> Tom Carrio <i class=\"ph ph-graph\"></i>"
subtitles = [
    "<i class=\"ph ph-map-pin\"></i> Detroit, MI",
    "<i class=\"ph ph-code-block\"></i> Staff Engineer",
    "<i class=\"ph ph-tree-view\"></i> Observability Expert",
    "<i class=\"ph ph-users-three\"></i> Engineering Manager",
    "<i class=\"ph ph-git-branch\"></i> Open Source Maintainer"
]

[extra.after_dark.blog]
menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/blog", name = "Blog"},
    {url = "$BASE_URL/tags", name = "Tags"},
]
