name: Zola on GitHub Pages

on:
  push:
    branches:
      - main 
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/gh-pages'
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.0.0
        with:
          submodules: true
      - name: Transfer theme data
        run: |
          mkdir ./sass ./templates
          cp -r ./themes/after-dark/sass/*      ./sass/
          cp -r ./themes/after-dark/templates/* ./templates/
      - name: Build only 
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts
          # A GitHub token is not necessary when BUILD_ONLY is true
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.0.0
        with:
          submodules: true
      - name: Transfer theme data
        run: |
          mkdir ./sass ./templates
          cp -r ./themes/after-dark/sass/*      ./sass/
          cp -r ./themes/after-dark/templates/* ./templates/
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
